using UnityEngine;
using UnityEngine.UI;

public class PlayerMovementV2 : MonoBehaviour
{
    private float moveS;
    public float walkS;
    public float sprintS;

    public Transform lookDir;
    public Slider staminaBar;

    float horiInput;
    float vertInput;

    Vector3 moveDir;

    Rigidbody rb;

    public float heightOfPlayer;
    public LayerMask ground;
    bool onGround;

    public float dragOnGround;

    public float jumpForce;
    public float cooldownJump;
    public float inAirMulti;
    bool jumpable = true;

    public float currentStam;
    public float maxStam;
    public float stamDrain;
    public float stamRecharge;
    bool sprinting = false;

    public float maxSlope;
    private RaycastHit slopeHit;
    private bool slopeExit;

    public MovementState state;
    public enum MovementState
    {
        walking,
        sprinting,
        air
    }

    float t = 0f;
    float startValue;
    float targetValue;

    void Start()
    {
        Physics.IgnoreLayerCollision(LayerMask.NameToLayer("Player"), LayerMask.NameToLayer("Dagger"), true);
        rb = GetComponent<Rigidbody>();
        rb.freezeRotation = true;

        staminaBar.maxValue = maxStam;
        staminaBar.minValue = 0;
        staminaBar.value = currentStam;
        startValue = currentStam;
        targetValue = currentStam;
    }

    void Update()
    {
        onGround = Physics.Raycast(transform.position, Vector3.down, heightOfPlayer * 0.5f + 0.2f, ground);
        PlayerInput();
        SpeedController();
        PlayerState();
        SprintBarUpdate();

        if (t < 0.1f)
        {
            t += Time.deltaTime;
            float n = t / 0.1f;
            n = 1f - Mathf.Pow(1f - n, 3f);
            staminaBar.value = Mathf.Lerp(startValue, targetValue, n);
        }

        if (onGround)
        {
            rb.linearDamping = dragOnGround;
        }
        else
        {
            rb.linearDamping = 0;
        }
    }

    void FixedUpdate()
    {
        PlayerMovement();
    }

    void PlayerInput()
    {
        horiInput = Input.GetAxisRaw("Horizontal");
        vertInput = Input.GetAxisRaw("Vertical");

        if (Input.GetKey(KeyCode.Space) && jumpable && onGround)
        {
            jumpable = false;
            Jump();
            Invoke(nameof(JumpReset), cooldownJump);
        }
    }

    private void PlayerState()
    {
        if (onGround && Input.GetKey(KeyCode.LeftShift) && currentStam > 0)
        {
            state = MovementState.sprinting;
            moveS = sprintS;
            sprinting = true;
        }
        else if (onGround)
        {
            state = MovementState.walking;
            moveS = walkS;
            sprinting = false;
        }
        else
        {
            state = MovementState.air;
            sprinting = false;
        }
    }

    private void SprintBarUpdate()
    {
        if (sprinting)
        {
            float newStamina = currentStam - stamDrain * Time.deltaTime;
            newStamina = Mathf.Clamp(newStamina, 0, maxStam);

            if (newStamina != currentStam)
            {
                startValue = staminaBar.value;
                targetValue = newStamina;
                t = 0f;
                currentStam = newStamina;
            }
        }

        if (!sprinting && currentStam < maxStam)
        {
            float newStamina = currentStam + stamRecharge * Time.deltaTime;
            newStamina = Mathf.Clamp(newStamina, 0, maxStam);

            if (newStamina != currentStam)
            {
                startValue = staminaBar.value;
                targetValue = newStamina;
                t = 0f;
                currentStam = newStamina;
            }
        }
    }

    private void PlayerMovement()
    {
        moveDir = lookDir.forward * vertInput + lookDir.right * horiInput;

        if (PlayerOnSlope() && !slopeExit)
        {
            Vector3 slopeDirection = Vector3.ProjectOnPlane(moveDir, slopeHit.normal).normalized;
            rb.AddForce(slopeDirection * moveS * 1000f, ForceMode.Force);
        }
        else if (onGround)
        {
            rb.AddForce(moveDir.normalized * moveS * 12f, ForceMode.Force);
        }
        else if (!onGround)
        {
            rb.AddForce(moveDir.normalized * moveS * 12f * inAirMulti, ForceMode.Force);
        }

        rb.useGravity = !PlayerOnSlope();
    }

    private bool PlayerOnSlope()
    {
        Vector3 rayOrigin = transform.position + Vector3.up * 0.1f;

        if (Physics.Raycast(rayOrigin, Vector3.down, out slopeHit, heightOfPlayer * 0.5f + 0.4f, ground))
        {
            float angle = Vector3.Angle(Vector3.up, slopeHit.normal);
            return angle < maxSlope && angle != 0;
        }

        return false;
    }

    private void SpeedController()
    {
        Vector3 velocityFlat = new Vector3(rb.linearVelocity.x, 0f, rb.linearVelocity.z);

        if (velocityFlat.magnitude > moveS)
        {
            Vector3 velocityLimit = velocityFlat.normalized * moveS;
            rb.linearVelocity = new Vector3(velocityLimit.x, rb.linearVelocity.y, velocityLimit.z);
        }
    }

    private void Jump()
    {
        slopeExit = true;
        rb.linearVelocity = new Vector3(rb.linearVelocity.x, 0f, rb.linearVelocity.z);
        rb.AddForce(transform.up * jumpForce, ForceMode.Impulse);
    }

    private void JumpReset()
    {
        slopeExit = false;
        jumpable = true;
    }
}
